# Impact of mood on music

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2
import seaborn as sns
import scipy.stats
import scipy.stats as stats
from scipy.stats import chi2_contingency


## Loading the data

In [2]:
data = pd.read_csv('Impact of Mood on Music Final.csv')

In [3]:
data.head(5)

Name  Gender  Age    Marital Status        Area Religion  \
0  Raminder Singh Bindra    Male   43           Married  Urban Area     Sikh   
1                  Santy    Male   19  Unmarried/Single  Urban Area   Muslim   
2          Cherry Khaund  Female   48          Divorced  Urban Area    Hindu   
3               Alifiya   Female   19  Unmarried/Single  Urban Area   Muslim   
4          Aishna tejpal  Female   18  Unmarried/Single  Urban Area    Hindu   

       Occupation How frequently do you listen to music?  \
0    Entrepreneur                              Every day   
1         Student                              Every day   
2  Private Sector                              Every day   
3         Student                              Every day   
4         Student                              Every day   

   How many hours do you stream music in a week (In hours) ?  \
0                                                2.0           
1                                               48.0           
2                                               28.0           
3                                               26.0           
4                                               14.0           

  What do you prefer for streaming music ?  ...  \
0                                    Video  ...   
1                                    Audio  ...   
2                                    Video  ...   
3                                    Audio  ...   
4                                    Audio  ...   

  Which language do you prefer to listen to when you are Excited/Energetic ?  \
0                                            Punjabi                           
1                                            English                           
2                                              Hindi                           
3                                              Hindi                           
4                                            English                           

  Which genre will you listen or prefer to listen to when you are Sentimental/Nostalgic ?  \
0                                                Pop                                        
1                                            Hip-Hop                                        
2                                            Hip-Hop                                        
3                              Musicals/Instrumental                                        
4                                                Pop                                        

  Which language do you prefer to listen to when you are Sentimental/Nostalgic ?  \
0                                              Hindi                               
1                                            English                               
2                                              Hindi                               
3                                              Hindi                               
4                                            English                               

  Which genre will you listen or prefer to listen to when you are feeling Inspired ?  \
0                                                Pop                                   
1                                               Rock                                   
2                                            Hip-Hop                                   
3                                                Rap                                   
4                                                Pop                                   

  Which language do you prefer to listen to when you are feeling Inspired ?  \
0                                            Punjabi                          
1                                            English                          
2                                              Hindi                          
3                                              Hindi                          
4                

In [4]:
data.isnull().sum()

Name                                                                                          0
Gender                                                                                        0
Age                                                                                           0
Marital Status                                                                                0
Area                                                                                          0
Religion                                                                                      0
Occupation                                                                                    0
How frequently do you listen to music?                                                        0
How many hours do you stream music in a week (In hours) ?                                     0
What do you prefer for streaming music ?                                                      0
Which device do you use for streaming mu

## Data Description

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 46 columns):
 #   Column                                                                                      Non-Null Count  Dtype  
---  ------                                                                                      --------------  -----  
 0   Name                                                                                        213 non-null    object 
 1   Gender                                                                                      213 non-null    object 
 2   Age                                                                                         213 non-null    int64  
 3   Marital Status                                                                              213 non-null    object 
 4   Area                                                                                        213 non-null    object 
 5   Religion                                   

In [6]:
data.describe()

Age  How many hours do you stream music in a week (In hours) ?
count  213.000000                                         213.000000        
mean    26.661972                                          15.793427        
std     11.092591                                          16.653009        
min     15.000000                                           0.000000        
25%     19.000000                                           4.000000        
50%     21.000000                                          10.000000        
75%     31.000000                                          20.000000        
max     70.000000                                          90.000000

In [7]:
data.shape

(213, 46)

In [8]:
language_mapping = {
    'Malayali': 'South Indian',
    'Telugu': 'South Indian',
    'Tamil': 'South Indian',
    'Kannada': 'South Indian',
    'Korean': 'Foreign',
    'Spanish': 'Foreign',
    'English':'English',
    'Hindi':'Hindi',
    'Punjabi':'Punjabi'
}

data['Language_happy'] = data['Which language do you prefer to listen to when you are Happy ?'].map(language_mapping)
data['Language_sad'] = data['Which language do you prefer to listen to when you are Sad/Emotional ?'].map(language_mapping)
data['Language_angry'] = data['Which language do you prefer to listen to when you are Angry/Aggressive ?'].map(language_mapping)
data['Language_calm'] = data['Which language do you prefer to listen to when you are Calm/Relaxed ?'].map(language_mapping)
data['Language_anxious'] = data['Which language do you prefer to listen to when you are Anxious ?'].map(language_mapping)
data['Language_excited'] = data['Which language do you prefer to listen to when you are Excited/Energetic ?'].map(language_mapping)
data['Language_sentimental'] = data['Which language do you prefer to listen to when you are Sentimental/Nostalgic ?'].map(language_mapping)
data['Language_inspired'] = data['Which language do you prefer to listen to when you are feeling Inspired ?'].map(language_mapping)
data['Language_compassionate'] = data['Which language do you prefer to listen to when you are  Empathetic/Compassionate ?'].map(language_mapping)
data['Language_romantic'] = data['Which language do you prefer to listen to when you are feeling Romantic ?'].map(language_mapping)






In [9]:
genre_mapping = {
    'Pop': 'Pop',
    'Hip-Hop': 'Hip-Hop',
    'Classical': 'Classical',
    'Indie': 'Indie,R&B',
    'Musicals/Instrumental': 'Musicals/Instrumental',
    'R&B': 'Indie,R&B',
    'Rock': 'Rock',
    'Techno': 'Techno',
}

data['Genre_happy'] = data['Which genre will you listen or prefer to listen to when you are Happy ?'].map(genre_mapping)
data['Genre_sad']=data['Which genre will you listen or prefer to listen to when you are Sad/Emotional ?'].map(genre_mapping)
data['Genre_angry']=data['Which genre will you listen or prefer to listen to when you are Angry/Aggressive ?'].map(genre_mapping)
data['Genre_calm']=data['Which genre will you listen or prefer to listen to when you are Calm/Relaxed ?'].map(genre_mapping)
data['Genre_anxious']=data['Which genre will you listen or prefer to listen to when you are Anxious ?'].map(genre_mapping)
data['Genre_excited']=data['Which genre will you listen or prefer to listen to when you are Excited/Energetic ?'].map(genre_mapping)
data['Genre_sentimental']=data['Which genre will you listen or prefer to listen to when you are Sentimental/Nostalgic ?'].map(genre_mapping)
data['Genre_inspired']=data['Which genre will you listen or prefer to listen to when you are feeling Inspired ?'].map(genre_mapping)
data['Genre_compassionate']=data['Which genre will you listen or prefer to listen to when you are Empathetic/Compassionate ?'].map(genre_mapping)
data['Genre_romantic']=data['Which genre will you listen or prefer to listen to when you are feeling Romantic ?'].map(genre_mapping)





## Objective 1 To study the impact of emotional states on different genre of music and language

In [10]:
observed_values_happy_gl = pd.crosstab(data['Genre_happy'], data['Language_happy'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_happy_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 71.77263459280452
P-value: 1.1746014314225404e-06
Degrees of freedom: 24
Expected values:
[[10.22513089  1.53926702  6.26701571  1.53926702  1.42931937]
 [35.54450262  5.35078534 21.78534031  5.35078534  4.96858639]
 [ 6.32984293  0.95287958  3.87958115  0.95287958  0.88481675]
 [ 5.35602094  0.80628272  3.28272251  0.80628272  0.7486911 ]
 [21.91099476  3.29842932 13.42931937  3.29842932  3.06282723]
 [12.17277487  1.83246073  7.46073298  1.83246073  1.70157068]
 [ 1.46073298  0.21989529  0.89528796  0.21989529  0.20418848]]


In [11]:
observed_values_happy_gl

Language_happy         English  Foreign  Hindi  Punjabi  South Indian
Genre_happy                                                          
Classical                    4        1      8        1             7
Hip-Hop                     44        7     17        5             0
Indie,R&B                    4        0      8        1             0
Musicals/Instrumental        4        0      5        0             2
Pop                         20        5     13        5             2
Rock                        17        1      5        2             0
Techno                       0        0      1        0             2

In [12]:
#data['Codes_sad_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Sad/Emotional ?']).codes
#data['Codes_sad_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Sad/Emotional ?']).codes


observed_values_sad_gl = pd.crosstab(data['Genre_sad'], data['Language_sad'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_sad_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 82.44437191247563
P-value: 2.4701836208466193e-08
Degrees of freedom: 24
Expected values:
[[15.61904762  1.14285714 15.80952381  0.57142857  2.85714286]
 [18.65608466  1.36507937 18.88359788  0.68253968  3.41269841]
 [13.44973545  0.98412698 13.61375661  0.49206349  2.46031746]
 [20.82539683  1.52380952 21.07936508  0.76190476  3.80952381]
 [ 7.80952381  0.57142857  7.9047619   0.28571429  1.42857143]
 [ 4.33862434  0.31746032  4.39153439  0.15873016  0.79365079]
 [ 1.3015873   0.0952381   1.31746032  0.04761905  0.23809524]]


In [13]:
observed_values_sad_gl

Language_sad           English  Foreign  Hindi  Punjabi  South Indian
Genre_sad                                                            
Classical                    7        0     24        0             5
Hip-Hop                     26        2     14        0             1
Indie,R&B                   17        3     10        1             0
Musicals/Instrumental       14        0     27        1             6
Pop                          9        1      7        1             0
Rock                         9        0      1        0             0
Techno                       0        0      0        0             3

In [14]:
#data['Codes_angry_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Angry/Aggressive ?']).codes
#data['Codes_angry_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Angry/Aggressive ?']).codes


observed_values_angry_gl = pd.crosstab(data['Genre_angry'],data['Language_angry'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_angry_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 51.785150749127084
P-value: 0.0008344527461156702
Degrees of freedom: 24
Expected values:
[[ 8.15189873  0.62025316  3.72151899  0.53164557  0.97468354]
 [25.03797468  1.90506329 11.43037975  1.63291139  2.99367089]
 [ 4.07594937  0.31012658  1.86075949  0.26582278  0.48734177]
 [14.55696203  1.10759494  6.64556962  0.94936709  1.74050633]
 [ 8.73417722  0.66455696  3.98734177  0.56962025  1.0443038 ]
 [26.78481013  2.03797468 12.2278481   1.74683544  3.20253165]
 [ 4.65822785  0.35443038  2.12658228  0.30379747  0.55696203]]


In [15]:
observed_values_angry_gl

Language_angry         English  Foreign  Hindi  Punjabi  South Indian
Genre_angry                                                          
Classical                    3        1      6        0             4
Hip-Hop                     26        4     10        2             1
Indie,R&B                    5        0      2        0             0
Musicals/Instrumental        9        1     11        0             4
Pop                          8        0      5        2             0
Rock                        36        0      8        2             0
Techno                       5        1      0        0             2

In [16]:
#data['Codes_calm_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Calm/Relaxed ?']).codes
#data['Codes_calm_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Calm/Relaxed ?']).codes


observed_values_calm_gl = pd.crosstab(data['Genre_calm'], data['Language_calm'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_calm_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 56.97164620122172
P-value: 0.0001687560835809992
Degrees of freedom: 24
Expected values:
[[17.94416244  1.95431472 12.43654822  0.53299492  2.1319797 ]
 [25.63451777  2.79187817 17.76649746  0.76142132  3.04568528]
 [17.94416244  1.95431472 12.43654822  0.53299492  2.1319797 ]
 [23.58375635  2.56852792 16.34517766  0.70050761  2.80203046]
 [10.25380711  1.11675127  7.10659898  0.30456853  1.21827411]
 [ 4.10152284  0.44670051  2.84263959  0.12182741  0.48730964]
 [ 1.53807107  0.16751269  1.06598985  0.04568528  0.18274112]]


In [17]:
observed_values_calm_gl

Language_calm          English  Foreign  Hindi  Punjabi  South Indian
Genre_calm                                                           
Classical                   10        0     20        0             5
Hip-Hop                     29        6     15        0             0
Indie,R&B                   21        2     10        0             2
Musicals/Instrumental       21        0     21        1             3
Pop                         11        2      4        2             1
Rock                         8        0      0        0             0
Techno                       1        1      0        0             1

In [18]:
#data['Codes_anxious_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Anxious ?']).codes
#data['Codes_anxious_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Anxious ?']).codes


observed_values_anxious_gl = pd.crosstab(data['Genre_anxious'], data['Language_anxious'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_anxious_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 52.74335276290678
P-value: 0.0006252919841045836
Degrees of freedom: 24
Expected values:
[[16.75879397  1.16582915  8.74371859  0.87437186  1.45728643]
 [22.53768844  1.5678392  11.75879397  1.1758794   1.95979899]
 [22.53768844  1.5678392  11.75879397  1.1758794   1.95979899]
 [30.6281407   2.13065327 15.9798995   1.59798995  2.66331658]
 [10.9798995   0.7638191   5.72864322  0.57286432  0.95477387]
 [10.40201005  0.72361809  5.42713568  0.54271357  0.90452261]
 [ 1.15577889  0.08040201  0.60301508  0.06030151  0.10050251]]


In [19]:
observed_values_anxious_gl

Language_anxious       English  Foreign  Hindi  Punjabi  South Indian
Genre_anxious                                                        
Classical                    8        0     16        1             4
Hip-Hop                     24        3     11        1             0
Indie,R&B                   27        3      8        1             0
Musicals/Instrumental       32        0     17        0             4
Pop                          8        2      7        2             0
Rock                        15        0      1        1             1
Techno                       1        0      0        0             1

In [20]:
#data['Codes_excited_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Excited/Energetic ?']).codes
#data['Codes_excited_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Excited/Energetic ?']).codes


observed_values_excited_gl = pd.crosstab(data['Genre_excited'], data['Language_excited'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_excited_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 66.43180830297214
P-value: 7.487140839729117e-06
Degrees of freedom: 24
Expected values:
[[ 5.51871658  0.70588235  3.78609626  1.28342246  0.70588235]
 [43.22994652  5.52941176 29.65775401 10.05347594  5.52941176]
 [ 3.21925134  0.41176471  2.20855615  0.7486631   0.41176471]
 [ 3.21925134  0.41176471  2.20855615  0.7486631   0.41176471]
 [13.79679144  1.76470588  9.46524064  3.20855615  1.76470588]
 [13.79679144  1.76470588  9.46524064  3.20855615  1.76470588]
 [ 3.21925134  0.41176471  2.20855615  0.7486631   0.41176471]]


In [21]:
observed_values_excited_gl

Language_excited       English  Foreign  Hindi  Punjabi  South Indian
Genre_excited                                                        
Classical                    4        0      4        0             4
Hip-Hop                     43        7     27       16             1
Indie,R&B                    2        0      2        1             2
Musicals/Instrumental        1        0      6        0             0
Pop                          8        4     13        3             2
Rock                        22        0      7        0             1
Techno                       6        0      0        0             1

In [22]:
#data['Codes_sentimental_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Sentimental/Nostalgic ?']).codes
#data['Codes_sentimental_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are Sentimental/Nostalgic ?']).codes


observed_values_sentimental_gl = pd.crosstab(data['Genre_sentimental'], data['Language_sentimental'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_sentimental_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 48.68831866030193
P-value: 0.0020724266093232113
Degrees of freedom: 24
Expected values:
[[23.95454545  1.54545455 21.63636364  1.03030303  2.83333333]
 [14.56060606  0.93939394 13.15151515  0.62626263  1.72222222]
 [23.01515152  1.48484848 20.78787879  0.98989899  2.72222222]
 [15.96969697  1.03030303 14.42424242  0.68686869  1.88888889]
 [ 9.86363636  0.63636364  8.90909091  0.42424242  1.16666667]
 [ 4.6969697   0.3030303   4.24242424  0.2020202   0.55555556]
 [ 0.93939394  0.06060606  0.84848485  0.04040404  0.11111111]]


In [23]:
observed_values_anxious_gl

Language_anxious       English  Foreign  Hindi  Punjabi  South Indian
Genre_anxious                                                        
Classical                    8        0     16        1             4
Hip-Hop                     24        3     11        1             0
Indie,R&B                   27        3      8        1             0
Musicals/Instrumental       32        0     17        0             4
Pop                          8        2      7        2             0
Rock                        15        0      1        1             1
Techno                       1        0      0        0             1

In [24]:
#data['Codes_inspired_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are feeling Inspired ?']).codes
#data['Codes_inspired_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are feeling Inspired ?']).codes


observed_values_inspired_gl = pd.crosstab(data['Genre_inspired'], data['Language_inspired'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_inspired_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 80.27692079331655
P-value: 5.496137536187778e-08
Degrees of freedom: 24
Expected values:
[[10.34254144  1.09392265  4.67403315  0.6961326   1.19337017]
 [35.62430939  3.7679558  16.09944751  2.39779006  4.11049724]
 [ 9.7679558   1.03314917  4.41436464  0.65745856  1.12707182]
 [11.49171271  1.21546961  5.19337017  0.77348066  1.32596685]
 [16.08839779  1.70165746  7.27071823  1.08287293  1.85635359]
 [20.11049724  2.12707182  9.08839779  1.35359116  2.32044199]
 [ 0.57458564  0.06077348  0.25966851  0.03867403  0.06629834]]


In [25]:
observed_values_inspired_gl

Language_inspired      English  Foreign  Hindi  Punjabi  South Indian
Genre_inspired                                                       
Classical                    3        0     10        0             5
Hip-Hop                     46        3     12        1             0
Indie,R&B                    8        2      5        1             1
Musicals/Instrumental        5        0     11        0             4
Pop                         12        5      9        2             0
Rock                        29        1      0        3             2
Techno                       1        0      0        0             0

In [26]:
#data['Codes_Compassionate_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Empathetic/Compassionate ?']).codes
#data['Codes_Compassionate_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are  Empathetic/Compassionate ?']).codes


observed_values_Compassionate_gl = pd.crosstab(data['Genre_compassionate'], data['Language_compassionate'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_Compassionate_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 60.75473860109253
P-value: 4.994137459395187e-05
Degrees of freedom: 24
Expected values:
[[25.24137931  0.82758621 12.82758621  0.82758621  2.27586207]
 [27.04433498  0.88669951 13.74384236  0.88669951  2.43842365]
 [16.82758621  0.55172414  8.55172414  0.55172414  1.51724138]
 [24.03940887  0.78817734 12.21674877  0.78817734  2.16748768]
 [16.22660099  0.5320197   8.24630542  0.5320197   1.46305419]
 [11.41871921  0.37438424  5.80295567  0.37438424  1.02955665]
 [ 1.20197044  0.03940887  0.61083744  0.03940887  0.10837438]]


In [27]:
observed_values_Compassionate_gl

Language_compassionate  English  Foreign  Hindi  Punjabi  South Indian
Genre_compassionate                                                   
Classical                    14        0     20        0             8
Hip-Hop                      36        0      9        0             0
Indie,R&B                    15        1     10        1             1
Musicals/Instrumental        24        0     14        0             2
Pop                          17        3      5        2             0
Rock                         15        0      3        1             0
Techno                        1        0      1        0             0

In [28]:
#data['Codes_romantic_genre'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are feeling Romantic ?']).codes
#data['Codes_romantic_language'] = pd.Categorical(data['Which language do you prefer to listen to when you are feeling Romantic ?']).codes


observed_values_romantic_gl = pd.crosstab(data['Genre_romantic'], data['Language_romantic'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_romantic_gl)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 68.4664302519623
P-value: 3.7235464382893334e-06
Degrees of freedom: 24
Expected values:
[[19.78846154  0.40384615 18.57692308  0.40384615  2.82692308]
 [23.08653846  0.47115385 21.67307692  0.47115385  3.29807692]
 [13.66346154  0.27884615 12.82692308  0.27884615  1.95192308]
 [15.54807692  0.31730769 14.59615385  0.31730769  2.22115385]
 [19.31730769  0.39423077 18.13461538  0.39423077  2.75961538]
 [ 5.18269231  0.10576923  4.86538462  0.10576923  0.74038462]
 [ 1.41346154  0.02884615  1.32692308  0.02884615  0.20192308]]


In [29]:
observed_values_romantic_gl

Language_romantic      English  Foreign  Hindi  Punjabi  South Indian
Genre_romantic                                                       
Classical                   16        0     20        1             5
Hip-Hop                     29        1     19        0             0
Indie,R&B                   13        0     13        0             3
Musicals/Instrumental        9        0     23        0             1
Pop                         20        1     17        0             3
Rock                        10        0      0        0             1
Techno                       1        0      0        1             1

## Objective 2
## To study the association between socio-demographic variables with factors frequency of
## listening, usage, streaming platforms, purpose of music
-


## Freq of usage

In [30]:

bins = [0, 10, 20,30, float('inf')]


labels = ['0-10', '20', '20-30', '30+']


data['stream_hours'] = pd.cut(data['How many hours do you stream music in a week (In hours) ?'], bins=bins, labels=labels, right=False)



provided_data = pd.DataFrame({
    'Range': ['10-20', '20-30', '30+'],
    'Count': [59, 24, 130]
})

In [31]:


bins = [15, 20, 25, 26, 40, float('inf')]


labels = ['15-19', '20', '25', '26-39', '40+']


data['Age_Group'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)




In [32]:
#data['Genre_Codes'] = pd.Categorical(data[).code
observed_values_freq_gender = pd.crosstab(data['stream_hours'],data['Gender'])

chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_freq_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)


Chi-squared statistic: 1.3677835693097258
P-value: 0.7131035085378186
Degrees of freedom: 3
Expected values:
[[51.63380282 42.36619718]
 [32.4084507  26.5915493 ]
 [13.18309859 10.81690141]
 [19.77464789 16.22535211]]


In [33]:
observed_values_freq_gender

Gender        Female  Male
stream_hours              
0-10              55    39
20                32    27
20-30             13    11
30+               17    19

In [34]:
#data['Genre_Codes'] = pd.Categorical(data[).code
observed_values_freq_age = pd.crosstab(data['stream_hours'],data['Age_Group'])

chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_freq_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)


Chi-squared statistic: 57.37893891586902
P-value: 4.275725373905414e-09
Degrees of freedom: 9
Expected values:
[[23.83098592 37.95305164 16.76995305 15.44600939]
 [14.95774648 23.82159624 10.5258216   9.69483568]
 [ 6.08450704  9.69014085  4.28169014  3.94366197]
 [ 9.12676056 14.53521127  6.42253521  5.91549296]]


In [35]:
observed_values_freq_age

Age_Group     15-19  20  26-39  40+
stream_hours                       
0-10             21  17     31   25
20               12  36      5    6
20-30             9  12      1    2
30+              12  21      1    2

In [36]:
#data['Genre_Codes'] = pd.Categorical(data[).codes


observed_values_freq_occupation = pd.crosstab(data['stream_hours'], data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_freq_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 38.21691848883011
P-value: 0.00014151010554786048
Degrees of freedom: 12
Expected values:
[[ 6.61971831 20.30046948  3.53051643 56.92957746  6.61971831]
 [ 4.15492958 12.74178404  2.21596244 35.73239437  4.15492958]
 [ 1.69014085  5.18309859  0.90140845 14.53521127  1.69014085]
 [ 2.53521127  7.77464789  1.35211268 21.8028169   2.53521127]]


In [37]:
round(0.00014151010554786048,5)

0.00014

In [38]:
observed_values_freq_occupation

Occupation    Entrepreneur  Private Sector  Public/Govt. Sector  Student  \
stream_hours                                                               
0-10                    12              27                    7       38   
20                       2              13                    0       40   
20-30                    1               2                    0       20   
30+                      0               4                    1       31   

Occupation    Unemployed/Not working  
stream_hours                          
0-10                              10  
20                                 4  
20-30                              1  
30+                                0

## Type of streaming

In [39]:
#data['Genre_Codes_streaming'] = pd.Categorical(data['What do you prefer for streaming music ?']).codes


observed_values_streaming_gender = pd.crosstab(data['What do you prefer for streaming music ?'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_streaming_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 0.00298960924543945
P-value: 0.9563955389057186
Degrees of freedom: 1
Expected values:
[[110.4084507  90.5915493]
 [  6.5915493   5.4084507]]


In [40]:
observed_values_streaming_gender

Gender                                    Female  Male
What do you prefer for streaming music ?              
Audio                                        111    90
Video                                          6     6

In [41]:
#data['Genre_Codes_streaming'] = pd.Categorical(data['What do you prefer for streaming music ?']).codes


observed_values_streaming_age = pd.crosstab(data['What do you prefer for streaming music ?'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_streaming_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 19.224224697460414
P-value: 0.00024570981584039686
Degrees of freedom: 3
Expected values:
[[50.95774648 81.15492958 35.85915493 33.02816901]
 [ 3.04225352  4.84507042  2.14084507  1.97183099]]


In [42]:
round( 0.00024570981584039686,5
     )

0.00025

In [43]:
observed_values_streaming_age

Age_Group                                 15-19  20  26-39  40+
What do you prefer for streaming music ?                       
Audio                                        54  85     33   29
Video                                         0   1      5    6

In [44]:
#data['Genre_Codes_streaming'] = pd.Categorical(data['What do you prefer for streaming music ?']).codes


observed_values_streaming_occupation = pd.crosstab(data['What do you prefer for streaming music ?'],data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_streaming_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 21.32093196177857
P-value: 0.0002734855320665176
Degrees of freedom: 4
Expected values:
[[ 14.15492958  43.4084507    7.54929577 121.73239437  14.15492958]
 [  0.84507042   2.5915493    0.45070423   7.26760563   0.84507042]]


In [45]:
round(0.0002734855320665176,6)

0.000273

In [46]:
observed_values_streaming_occupation

Occupation                                Entrepreneur  Private Sector  \
What do you prefer for streaming music ?                                 
Audio                                               11              41   
Video                                                4               5   

Occupation                                Public/Govt. Sector  Student  \
What do you prefer for streaming music ?                                 
Audio                                                       7      128   
Video                                                       1        1   

Occupation                                Unemployed/Not working  
What do you prefer for streaming music ?                          
Audio                                                         14  
Video                                                          1

## Platform Used

In [47]:
platform_mapping = {
    'Spotify': 'Spotify',
    'Apple Music': 'Apple Music',
    'Amazon Prime': 'Others',
    'Gaana': 'Others',
    'Radio': 'Others',
    'Saavn': 'Others',
    'Wynkk': 'Others',
    'Youtube/Youtube Music': 'Youtube/Youtube Music'
}

data['Preferred_music_platform'] = data['Which music platform do you prefer to listen ?'].map(platform_mapping)


In [48]:
#data['Genre_Codes_platform'] = pd.Categorical(data['Which music platform do you prefer to listen ?']).codes


observed_values_platform_gender = pd.crosstab(data['Preferred_music_platform'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_platform_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 2.3754436227974525
P-value: 0.49822215343630616
Degrees of freedom: 3
Expected values:
[[17.57746479 14.42253521]
 [13.18309859 10.81690141]
 [68.11267606 55.88732394]
 [18.12676056 14.87323944]]


In [49]:
observed_values_platform_gender

Gender                    Female  Male
Preferred_music_platform              
Apple Music                   14    18
Others                        14    10
Spotify                       72    52
Youtube/Youtube Music         17    16

In [50]:
#data['Genre_Codes_platform'] = pd.Categorical(data['Which music platform do you prefer to listen ?']).codes


observed_values_platform_age = pd.crosstab(data['Preferred_music_platform'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_platform_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 77.61507561696664
P-value: 4.803553879822598e-13
Degrees of freedom: 9
Expected values:
[[ 8.11267606 12.92018779  5.70892019  5.25821596]
 [ 6.08450704  9.69014085  4.28169014  3.94366197]
 [31.43661972 50.0657277  22.12206573 20.37558685]
 [ 8.36619718 13.32394366  5.88732394  5.42253521]]


In [51]:
observed_values_platform_age

Age_Group                 15-19  20  26-39  40+
Preferred_music_platform                       
Apple Music                   9  15      4    4
Others                        0   5     11    8
Spotify                      43  62      9   10
Youtube/Youtube Music         2   4     14   13

In [52]:
round(4.803553879822598,3)

4.804

In [53]:
#data['Genre_Codes_platform'] = pd.Categorical(data['Which music platform do you prefer to listen ?']).codes


observed_values_platform_occupation = pd.crosstab(data['Preferred_music_platform'],data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_platform_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 98.09911587951336
P-value: 1.3112034426777344e-15
Degrees of freedom: 12
Expected values:
[[ 2.25352113  6.91079812  1.20187793 19.38028169  2.25352113]
 [ 1.69014085  5.18309859  0.90140845 14.53521127  1.69014085]
 [ 8.73239437 26.77934272  4.657277   75.09859155  8.73239437]
 [ 2.32394366  7.12676056  1.23943662 19.98591549  2.32394366]]


In [54]:
observed_values_platform_occupation

Occupation                Entrepreneur  Private Sector  Public/Govt. Sector  \
Preferred_music_platform                                                      
Apple Music                          7               2                    0   
Others                               4               9                    2   
Spotify                              2              15                    3   
Youtube/Youtube Music                2              20                    3   

Occupation                Student  Unemployed/Not working  
Preferred_music_platform                                   
Apple Music                    21                       2  
Others                          3                       6  
Spotify                        99                       5  
Youtube/Youtube Music           6                       2


-
## Purpose

### Entertainment and Enjoyment

In [55]:
#data['Genre_Codes_entertainment'] = pd.Categorical(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]']).codes


observed_values_entertainment_gender = pd.crosstab(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_entertainment_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)


Chi-squared statistic: 2.9643729009477364
P-value: 0.08511745557317871
Degrees of freedom: 1
Expected values:
[[  2.1971831   1.8028169]
 [114.8028169  94.1971831]]


In [56]:
round(0.08511745557317871,4)

0.0851

In [57]:
observed_values_entertainment_gender

Gender                                              Female  Male
What is the purpose of listening to music ? [En...              
No                                                       0     4
Yes                                                    117    92

In [58]:
#data['Genre_Codes_entertainment'] = pd.Categorical(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]']).codes


observed_values_entertainment_age = pd.crosstab(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_entertainment_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 4.558751543931598
P-value: 0.20710927017429182
Degrees of freedom: 3
Expected values:
[[ 1.01408451  1.61502347  0.71361502  0.657277  ]
 [52.98591549 84.38497653 37.28638498 34.342723  ]]


In [59]:
round(0.20710927017429182,4)

0.2071

In [60]:
observed_values_entertainment_age

Age_Group                                           15-19  20  26-39  40+
What is the purpose of listening to music ? [En...                       
No                                                      1   0      1    2
Yes                                                    53  86     37   33

In [61]:
#data['Genre_Codes_entertainment'] = pd.Categorical(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]']).codes


observed_values_entertainment_occupation = pd.crosstab(data['What is the purpose of listening to music ? [Entertainment and Enjoyment]'],data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_platform_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)



Chi-squared statistic: 98.09911587951336
P-value: 1.3112034426777344e-15
Degrees of freedom: 12
Expected values:
[[ 2.25352113  6.91079812  1.20187793 19.38028169  2.25352113]
 [ 1.69014085  5.18309859  0.90140845 14.53521127  1.69014085]
 [ 8.73239437 26.77934272  4.657277   75.09859155  8.73239437]
 [ 2.32394366  7.12676056  1.23943662 19.98591549  2.32394366]]


In [62]:
round(1.3112034426777344,4)

1.3112

In [63]:
observed_values_entertainment_occupation

Occupation                                          Entrepreneur  \
What is the purpose of listening to music ? [En...                 
No                                                             0   
Yes                                                           15   

Occupation                                          Private Sector  \
What is the purpose of listening to music ? [En...                   
No                                                               1   
Yes                                                             45   

Occupation                                          Public/Govt. Sector  \
What is the purpose of listening to music ? [En...                        
No                                                                    1   
Yes                                                                   7   

Occupation                                          Student  \
What is the purpose of listening to music ? [En...            
No                                                        1   
Yes                                                     128   

Occupation                                          Unemployed/Not working  
What is the purpose of listening to music ? [En...                          
No                                                                       1  
Yes                                                                     14

## Emotional expression

In [64]:
#data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_gender = pd.crosstab(data['What is the purpose of listening to music ? [Emotional Expression]'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 14.821727272370946
P-value: 0.00011816623096745434
Degrees of freedom: 1
Expected values:
[[29.66197183 24.33802817]
 [87.33802817 71.66197183]]


In [65]:
round(0.00011816623096745434,4)

0.0001

In [66]:
observed_values_emotional_gender

Gender                                              Female  Male
What is the purpose of listening to music ? [Em...              
No                                                      17    37
Yes                                                    100    59

In [67]:
#data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_age = pd.crosstab(data['What is the purpose of listening to music ? [Emotional Expression]'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 8.342017572574605
P-value: 0.03944759426290083
Degrees of freedom: 3
Expected values:
[[13.69014085 21.8028169   9.63380282  8.87323944]
 [40.30985915 64.1971831  28.36619718 26.12676056]]


In [68]:
round(0.03944759426290083,4)

0.0394

In [69]:
observed_values_emotional_age

Age_Group                                           15-19  20  26-39  40+
What is the purpose of listening to music ? [Em...                       
No                                                      6  24     13   11
Yes                                                    48  62     25   24

data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_marital = pd.crosstab(data['purpose_emotional'], filtered_df['Marital Status'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_marital)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_area = pd.crosstab(data['purpose_emotional'], data['Area'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_area)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_religion = pd.crosstab(data['purpose_emotional'], data['Religion'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_religion)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

In [70]:
#data['purpose_emotional'] = pd.Categorical(data['What is the purpose of listening to music ? [Emotional Expression]']).codes


observed_values_emotional_occupation = pd.crosstab(data['What is the purpose of listening to music ? [Emotional Expression]'], data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 11.485058035313681
P-value: 0.02162091949287268
Degrees of freedom: 4
Expected values:
[[ 3.8028169  11.66197183  2.02816901 32.70422535  3.8028169 ]
 [11.1971831  34.33802817  5.97183099 96.29577465 11.1971831 ]]


In [71]:
round(0.02162091949287268,4)

0.0216

In [72]:
observed_values_emotional_occupation

Occupation                                          Entrepreneur  \
What is the purpose of listening to music ? [Em...                 
No                                                             4   
Yes                                                           11   

Occupation                                          Private Sector  \
What is the purpose of listening to music ? [Em...                   
No                                                              16   
Yes                                                             30   

Occupation                                          Public/Govt. Sector  \
What is the purpose of listening to music ? [Em...                        
No                                                                    2   
Yes                                                                   6   

Occupation                                          Student  \
What is the purpose of listening to music ? [Em...            
No                                                       24   
Yes                                                     105   

Occupation                                          Unemployed/Not working  
What is the purpose of listening to music ? [Em...                          
No                                                                       8  
Yes                                                                      7

## Social and cultural bonding

In [73]:
#data['purpose_social'] = pd.Categorical(data['What is the purpose of listening to music ? [Social and Cultural Bonding(Events)]']).codes


observed_values_social_gender = pd.crosstab(data['What is the purpose of listening to music ? [Social and Cultural Bonding(Events)]'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_emotional_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 14.821727272370946
P-value: 0.00011816623096745434
Degrees of freedom: 1
Expected values:
[[29.66197183 24.33802817]
 [87.33802817 71.66197183]]


In [74]:
observed_values_social_gender

Gender                                              Female  Male
What is the purpose of listening to music ? [So...              
No                                                      41    44
Yes                                                     76    52

In [75]:
round(14.821727272370946,4)

14.8217

In [76]:
#data['Genre_Codes'] = pd.Categorical(data['Which genre will you listen or prefer to listen to when you are Happy ?']).codes


observed_values_social_age = pd.crosstab(data['What is the purpose of listening to music ? [Social and Cultural Bonding(Events)]'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_social_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 8.466185790335105
P-value: 0.0372983249883458
Degrees of freedom: 3
Expected values:
[[21.54929577 34.31924883 15.16431925 13.96713615]
 [32.45070423 51.68075117 22.83568075 21.03286385]]


In [77]:
round(0.0372983249883458,4)

0.0373

In [78]:
observed_values_social_age

Age_Group                                           15-19  20  26-39  40+
What is the purpose of listening to music ? [So...                       
No                                                     15  44     14   12
Yes                                                    39  42     24   23

In [79]:
observed_values_social_occupation = pd.crosstab(data['What is the purpose of listening to music ? [Social and Cultural Bonding(Events)]'], data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_social_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 4.383435371810504
P-value: 0.3565936237133433
Degrees of freedom: 4
Expected values:
[[ 5.98591549 18.35680751  3.19248826 51.47887324  5.98591549]
 [ 9.01408451 27.64319249  4.80751174 77.52112676  9.01408451]]


In [80]:
round(0.3565936237133433,4)

0.3566

In [81]:
observed_values_social_occupation

Occupation                                          Entrepreneur  \
What is the purpose of listening to music ? [So...                 
No                                                             4   
Yes                                                           11   

Occupation                                          Private Sector  \
What is the purpose of listening to music ? [So...                   
No                                                              18   
Yes                                                             28   

Occupation                                          Public/Govt. Sector  \
What is the purpose of listening to music ? [So...                        
No                                                                    2   
Yes                                                                   6   

Occupation                                          Student  \
What is the purpose of listening to music ? [So...            
No                                                       52   
Yes                                                      77   

Occupation                                          Unemployed/Not working  
What is the purpose of listening to music ? [So...                          
No                                                                       9  
Yes                                                                      6

## Inspiration and Motivation

In [82]:
observed_values_inspiration_gender = pd.crosstab(data['What is the purpose of listening to music ? [Inspiration and Motivation]'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_inspiration_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 5.484245125655193
P-value: 0.01918860395474019
Degrees of freedom: 1
Expected values:
[[48.88732394 40.11267606]
 [68.11267606 55.88732394]]


In [83]:
observed_values_inspiration_gender

Gender                                              Female  Male
What is the purpose of listening to music ? [In...              
No                                                      40    49
Yes                                                     77    47

In [84]:
round(0.01918860395474019,4)

0.0192

In [85]:
observed_values_inspiration_age = pd.crosstab(data['What is the purpose of listening to music ? [Inspiration and Motivation]'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_inspiration_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 13.96839862052191
P-value: 0.002948484746966099
Degrees of freedom: 3
Expected values:
[[22.56338028 35.9342723  15.87793427 14.62441315]
 [31.43661972 50.0657277  22.12206573 20.37558685]]


In [86]:
round(0.002948484746966099,4)

0.0029

In [87]:
observed_values_inspiration_age

Age_Group                                           15-19  20  26-39  40+
What is the purpose of listening to music ? [In...                       
No                                                     15  46     19    9
Yes                                                    39  40     19   26

In [88]:
observed_values_inspiration_occupation = pd.crosstab(data['What is the purpose of listening to music ? [Inspiration and Motivation]'], data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_inspiration_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 4.639759115401713
P-value: 0.3262957653554803
Degrees of freedom: 4
Expected values:
[[ 6.26760563 19.22065728  3.342723   53.90140845  6.26760563]
 [ 8.73239437 26.77934272  4.657277   75.09859155  8.73239437]]


In [89]:
round( 0.3262957653554803,4)

0.3263

In [90]:
observed_values_inspiration_occupation

Occupation                                          Entrepreneur  \
What is the purpose of listening to music ? [In...                 
No                                                             5   
Yes                                                           10   

Occupation                                          Private Sector  \
What is the purpose of listening to music ? [In...                   
No                                                              21   
Yes                                                             25   

Occupation                                          Public/Govt. Sector  \
What is the purpose of listening to music ? [In...                        
No                                                                    6   
Yes                                                                   2   

Occupation                                          Student  \
What is the purpose of listening to music ? [In...            
No                                                       51   
Yes                                                      78   

Occupation                                          Unemployed/Not working  
What is the purpose of listening to music ? [In...                          
No                                                                       6  
Yes                                                                      9

## Healing and Therapy

In [91]:
observed_values_healing_gender = pd.crosstab(data['What is the purpose of listening to music ? [Healing and Therapy]'], data['Gender'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_healing_gender)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 15.690157662424246
P-value: 7.46114136350922e-05
Degrees of freedom: 1
Expected values:
[[43.3943662 35.6056338]
 [73.6056338 60.3943662]]


In [92]:
observed_values_healing_gender

Gender                                              Female  Male
What is the purpose of listening to music ? [He...              
No                                                      29    50
Yes                                                     88    46

In [93]:
round(7.46114136350922,4)

7.4611

In [94]:
observed_values_healing_age = pd.crosstab(data['What is the purpose of listening to music ? [Healing and Therapy]'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_healing_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 15.802595748330663
P-value: 0.0012447010327345796
Degrees of freedom: 3
Expected values:
[[20.02816901 31.89671362 14.09389671 12.98122066]
 [33.97183099 54.10328638 23.90610329 22.01877934]]


In [95]:
round(0.0012447010327345796,4)

0.0012

In [96]:
observed_values_healing_age

Age_Group                                           15-19  20  26-39  40+
What is the purpose of listening to music ? [He...                       
No                                                     11  44     15    9
Yes                                                    43  42     23   26

In [97]:
observed_values_healing_occupation = pd.crosstab(data['What is the purpose of listening to music ? [Healing and Therapy]'], data['Occupation'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_healing_occupation)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 4.528400486305339
P-value: 0.3391931876220508
Degrees of freedom: 4
Expected values:
[[ 5.56338028 17.06103286  2.96713615 47.84507042  5.56338028]
 [ 9.43661972 28.93896714  5.03286385 81.15492958  9.43661972]]


In [98]:
round(0.3391931876220508,4)

0.3392

In [99]:
observed_values_healing_occupation

Occupation                                          Entrepreneur  \
What is the purpose of listening to music ? [He...                 
No                                                             4   
Yes                                                           11   

Occupation                                          Private Sector  \
What is the purpose of listening to music ? [He...                   
No                                                              20   
Yes                                                             26   

Occupation                                          Public/Govt. Sector  \
What is the purpose of listening to music ? [He...                        
No                                                                    5   
Yes                                                                   3   

Occupation                                          Student  \
What is the purpose of listening to music ? [He...            
No                                                       46   
Yes                                                      83   

Occupation                                          Unemployed/Not working  
What is the purpose of listening to music ? [He...                          
No                                                                       4  
Yes                                                                     11

## To study the association between socio-demographic variables with music genre,
## languages in each emotional state

### Genre

In [100]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

for emotion in emotion_categories:
    observed_values_genre_gender = pd.crosstab(data['Genre_' + emotion], data['Gender'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_genre_gender)

    print(f"Chi-squared statistic for Genre_{emotion}: {chi2}")
    print(f"P-value for Genre_{emotion}: {p}")
    print(f"Degrees of freedom for Genre_{emotion}: {dof}")
    print(f"Expected values for Genre_{emotion}:")
    print(expected)


Chi-squared statistic for Genre_happy: 9.311392372140698
P-value for Genre_happy: 0.15680804367948692
Degrees of freedom for Genre_happy: 6
Expected values for Genre_happy:
[[13.29166667  8.70833333]
 [44.10416667 28.89583333]
 [ 7.85416667  5.14583333]
 [ 6.64583333  4.35416667]
 [27.1875     17.8125    ]
 [15.10416667  9.89583333]
 [ 1.8125      1.1875    ]]
Chi-squared statistic for Genre_sad: 16.889621608628204
P-value for Genre_sad: 0.00969757706593627
Degrees of freedom for Genre_sad: 6
Expected values for Genre_sad:
[[22.05181347 15.94818653]
 [24.95336788 18.04663212]
 [17.98963731 13.01036269]
 [29.01554404 20.98445596]
 [10.44559585  7.55440415]
 [ 5.80310881  4.19689119]
 [ 1.74093264  1.25906736]]
Chi-squared statistic for Genre_angry: 16.477062333544534
P-value for Genre_angry: 0.011410010014937104
Degrees of freedom for Genre_angry: 6
Expected values for Genre_angry:
[[ 9.24528302  5.75471698]
 [26.50314465 16.49685535]
 [ 4.31446541  2.68553459]
 [15.40880503  9.59119497

In [101]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Genre_' + emotion], data['Gender'])
    observed_values_dict[emotion] = observed_values


for emotion in emotion_categories:
    print(f"Observed values for {emotion}:")
    print(observed_values_dict[emotion])


Observed values for happy:
Gender                 Female  Male
Genre_happy                        
Classical                  12    10
Hip-Hop                    39    34
Indie,R&B                  10     3
Musicals/Instrumental       7     4
Pop                        34    11
Rock                       13    12
Techno                      1     2
Observed values for sad:
Gender                 Female  Male
Genre_sad                          
Classical                  19    19
Hip-Hop                    18    25
Indie,R&B                  23     8
Musicals/Instrumental      31    19
Pop                        14     4
Rock                        7     3
Techno                      0     3
Observed values for angry:
Gender                 Female  Male
Genre_angry                        
Classical                   4    11
Hip-Hop                    28    15
Indie,R&B                   7     0
Musicals/Instrumental      18     7
Pop                        11     4
Rock                 

In [102]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

for emotion in emotion_categories:
    observed_values_genre_gender = pd.crosstab(data['Genre_' + emotion], data['Age_Group'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_genre_gender)

    print(f"Chi-squared statistic for Genre_{emotion}: {chi2}")
    print(f"P-value for Genre_{emotion}: {p}")
    print(f"Degrees of freedom for Genre_{emotion}: {dof}")
    print(f"Expected values for Genre_{emotion}:")
    print(expected)

Chi-squared statistic for Genre_happy: 62.6716292195096
P-value for Genre_happy: 7.518469610627e-07
Degrees of freedom for Genre_happy: 18
Expected values for Genre_happy:
[[ 5.72916667  8.13541667  4.125       4.01041667]
 [19.01041667 26.99479167 13.6875     13.30729167]
 [ 3.38541667  4.80729167  2.4375      2.36979167]
 [ 2.86458333  4.06770833  2.0625      2.00520833]
 [11.71875    16.640625    8.4375      8.203125  ]
 [ 6.51041667  9.24479167  4.6875      4.55729167]
 [ 0.78125     1.109375    0.5625      0.546875  ]]
Chi-squared statistic for Genre_sad: 82.10737636103904
P-value for Genre_sad: 3.6566382100223526e-10
Degrees of freedom for Genre_sad: 18
Expected values for Genre_sad:
[[10.43523316 13.97927461  6.89119171  6.69430052]
 [11.80829016 15.81865285  7.79792746  7.57512953]
 [ 8.51295337 11.40414508  5.62176166  5.4611399 ]
 [13.73056995 18.39378238  9.06735751  8.80829016]
 [ 4.94300518  6.62176166  3.2642487   3.17098446]
 [ 2.74611399  3.67875648  1.8134715   1.76165

In [103]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Genre_' + emotion], data['Age_Group'])
    observed_values_dict[emotion] = observed_values


for emotion in emotion_categories:
    print(f"Observed values for {emotion}:")
    print(observed_values_dict[emotion])

Observed values for happy:
Age_Group              15-19  20  26-39  40+
Genre_happy                                 
Classical                  4   2      7    9
Hip-Hop                   19  45      6    3
Indie,R&B                  4   1      6    2
Musicals/Instrumental      2   2      4    3
Pop                       16  10      7   12
Rock                       5  11      4    5
Techno                     0   0      2    1
Observed values for sad:
Age_Group              15-19  20  26-39  40+
Genre_sad                                   
Classical                 10   4     10   14
Hip-Hop                    9  31      3    0
Indie,R&B                 14  14      2    1
Musicals/Instrumental      9  12     17   12
Pop                       10   4      0    4
Rock                       1   5      1    3
Techno                     0   1      2    0
Observed values for angry:
Age_Group              15-19  20  26-39  40+
Genre_angry                                 
Classical            

In [104]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

for emotion in emotion_categories:
    observed_values_genre_gender = pd.crosstab(data['Genre_' + emotion], data['Occupation'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_genre_gender)

    print(f"Chi-squared statistic for Genre_{emotion}: {chi2}")
    print(f"P-value for Genre_{emotion}: {p}")
    print(f"Degrees of freedom for Genre_{emotion}: {dof}")
    print(f"Expected values for Genre_{emotion}:")
    print(expected)

Chi-squared statistic for Genre_happy: 62.656084128960835
P-value for Genre_happy: 2.668723806101622e-05
Degrees of freedom for Genre_happy: 24
Expected values for Genre_happy:
[[ 1.60416667  4.8125      0.91666667 13.0625      1.60416667]
 [ 5.32291667 15.96875     3.04166667 43.34375     5.32291667]
 [ 0.94791667  2.84375     0.54166667  7.71875     0.94791667]
 [ 0.80208333  2.40625     0.45833333  6.53125     0.80208333]
 [ 3.28125     9.84375     1.875      26.71875     3.28125   ]
 [ 1.82291667  5.46875     1.04166667 14.84375     1.82291667]
 [ 0.21875     0.65625     0.125       1.78125     0.21875   ]]
Chi-squared statistic for Genre_sad: 89.0239963263407
P-value for Genre_sad: 2.0898537533468506e-09
Degrees of freedom for Genre_sad: 24
Expected values for Genre_sad:
[[ 2.55958549  8.66321244  1.57512953 22.44559585  2.75647668]
 [ 2.89637306  9.80310881  1.78238342 25.39896373  3.11917098]
 [ 2.0880829   7.06735751  1.28497409 18.31088083  2.24870466]
 [ 3.36787565 11.3989637

In [105]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Genre_' + emotion], data['Occupation'])
    observed_values_dict[emotion] = observed_values


for emotion in emotion_categories:
    print(f"Observed values for {emotion}:")
    print(observed_values_dict[emotion])

Observed values for happy:
Occupation             Entrepreneur  Private Sector  Public/Govt. Sector  \
Genre_happy                                                                
Classical                         2               8                    3   
Hip-Hop                           3               9                    1   
Indie,R&B                         0               8                    0   
Musicals/Instrumental             2               4                    0   
Pop                               3               9                    2   
Rock                              3               4                    1   
Techno                            1               0                    1   

Occupation             Student  Unemployed/Not working  
Genre_happy                                             
Classical                    6                       3  
Hip-Hop                     59                       1  
Indie,R&B                    5                       0  
Mus

## Languages

In [106]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


for emotion in emotion_categories:
    observed_values_language_occupation = pd.crosstab(data['Language_' + emotion], data['Gender'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_language_occupation)

    print(f"Chi-squared statistic for Language_{emotion}: {chi2}")
    print(f"P-value for Language_{emotion}: {p}")
    print(f"Degrees of freedom for Language_{emotion}: {dof}")
    print(f"Expected values for Language_{emotion}:")
    print(expected)


Chi-squared statistic for Language_happy: 14.439616996505828
P-value for Language_happy: 0.006016427787875398
Degrees of freedom for Language_happy: 4
Expected values for Language_happy:
[[62.36320755 50.63679245]
 [ 7.72641509  6.27358491]
 [32.00943396 25.99056604]
 [ 7.72641509  6.27358491]
 [ 7.1745283   5.8254717 ]]
Chi-squared statistic for Language_sad: 16.515888888888888
P-value for Language_sad: 0.0023995779706113655
Degrees of freedom for Language_sad: 4
Expected values for Language_sad:
[[54.54545455 45.45454545]
 [ 3.27272727  2.72727273]
 [45.81818182 38.18181818]
 [ 1.63636364  1.36363636]
 [ 8.72727273  7.27272727]]
Chi-squared statistic for Language_angry: 14.469020491049479
P-value for Language_angry: 0.005939226600777016
Degrees of freedom for Language_angry: 4
Expected values for Language_angry:
[[76.16037736 61.83962264]
 [ 4.96698113  4.03301887]
 [24.83490566 20.16509434]
 [ 4.96698113  4.03301887]
 [ 6.07075472  4.92924528]]
Chi-squared statistic for Language_cal

In [107]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Language_' + emotion], data['Gender'])
    observed_values_dict[emotion] = observed_values

for emotion in emotion_categories:
    print(f"Observed values for Language_{emotion}:")
    print(observed_values_dict[emotion])


Observed values for Language_happy:
Gender          Female  Male
Language_happy              
English             52    61
Foreign             12     2
Hindi               40    18
Punjabi              6     8
South Indian         7     6
Observed values for Language_sad:
Gender        Female  Male
Language_sad              
English           44    56
Foreign            6     0
Hindi             56    28
Punjabi            2     1
South Indian       6    10
Observed values for Language_angry:
Gender          Female  Male
Language_angry              
English             72    66
Foreign              7     2
Hindi               32    13
Punjabi              1     8
South Indian         5     6
Observed values for Language_calm:
Gender         Female  Male
Language_calm              
English            55    56
Foreign             9     3
Hindi              46    26
Punjabi             1     2
South Indian        5     7
Observed values for Language_anxious:
Gender            Female  Male

In [108]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


for emotion in emotion_categories:
    observed_values_language_occupation = pd.crosstab(data['Language_' + emotion], data['Age_Group'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_language_occupation)

    print(f"Chi-squared statistic for Language_{emotion}: {chi2}")
    print(f"P-value for Language_{emotion}: {p}")
    print(f"Degrees of freedom for Language_{emotion}: {dof}")
    print(f"Expected values for Language_{emotion}:")
    print(expected)


Chi-squared statistic for Language_happy: 51.61578901179277
P-value for Language_happy: 7.250878177790507e-07
Degrees of freedom for Language_happy: 12
Expected values for Language_happy:
[[28.78301887 45.83962264 19.72169811 18.65566038]
 [ 3.56603774  5.67924528  2.44339623  2.31132075]
 [14.77358491 23.52830189 10.12264151  9.5754717 ]
 [ 3.56603774  5.67924528  2.44339623  2.31132075]
 [ 3.31132075  5.27358491  2.26886792  2.14622642]]
Chi-squared statistic for Language_sad: 44.01804907498535
P-value for Language_sad: 1.5163838310896563e-05
Degrees of freedom for Language_sad: 12
Expected values for Language_sad:
[[25.83732057 40.19138756 17.70334928 16.26794258]
 [ 1.55023923  2.41148325  1.06220096  0.97607656]
 [21.70334928 33.76076555 14.8708134  13.66507177]
 [ 0.77511962  1.20574163  0.53110048  0.48803828]
 [ 4.13397129  6.43062201  2.83253589  2.60287081]]
Chi-squared statistic for Language_angry: 57.41902518004079
P-value for Language_angry: 6.639863366471464e-08
Degrees o

In [109]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Language_' + emotion], data['Age_Group'])
    observed_values_dict[emotion] = observed_values

for emotion in emotion_categories:
    print(f"Observed values for Language_{emotion}:")
    print(observed_values_dict[emotion])


Observed values for Language_happy:
Age_Group       15-19  20  26-39  40+
Language_happy                       
English            35  58     10   10
Foreign             7   6      0    1
Hindi               6  16     17   19
Punjabi             4   3      4    3
South Indian        2   3      6    2
Observed values for Language_sad:
Age_Group     15-19  20  26-39  40+
Language_sad                       
English          28  54     10    8
Foreign           3   3      0    0
Hindi            19  21     19   25
Punjabi           2   0      1    0
South Indian      2   6      7    1
Observed values for Language_angry:
Age_Group       15-19  20  26-39  40+
Language_angry                       
English            40  72     13   13
Foreign             4   4      1    0
Hindi               9   6     15   15
Punjabi             0   1      4    4
South Indian        1   3      4    3
Observed values for Language_calm:
Age_Group      15-19  20  26-39  40+
Language_calm                       
E

In [110]:

emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']


for emotion in emotion_categories:
    observed_values_language_occupation = pd.crosstab(data['Language_' + emotion], data['Occupation'])
    
    chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_language_occupation)

    print(f"Chi-squared statistic for Language_{emotion}: {chi2}")
    print(f"P-value for Language_{emotion}: {p}")
    print(f"Degrees of freedom for Language_{emotion}: {dof}")
    print(f"Expected values for Language_{emotion}:")
    print(expected)


Chi-squared statistic for Language_happy: 64.5206214061857
P-value for Language_happy: 8.905851596996366e-08
Degrees of freedom for Language_happy: 16
Expected values for Language_happy:
[[ 7.99528302 23.98584906  4.26415094 68.75943396  7.99528302]
 [ 0.99056604  2.97169811  0.52830189  8.51886792  0.99056604]
 [ 4.10377358 12.31132075  2.18867925 35.29245283  4.10377358]
 [ 0.99056604  2.97169811  0.52830189  8.51886792  0.99056604]
 [ 0.91981132  2.75943396  0.49056604  7.91037736  0.91981132]]
Chi-squared statistic for Language_sad: 48.616563792993134
P-value for Language_sad: 3.7987414110064986e-05
Degrees of freedom for Language_sad: 16
Expected values for Language_sad:
[[ 7.17703349 21.53110048  3.8277512  60.76555024  6.69856459]
 [ 0.43062201  1.29186603  0.22966507  3.64593301  0.40191388]
 [ 6.02870813 18.0861244   3.215311   51.0430622   5.62679426]
 [ 0.215311    0.64593301  0.11483254  1.82296651  0.20095694]
 [ 1.14832536  3.44497608  0.61244019  9.72248804  1.07177033]]

In [111]:
emotion_categories = ['happy', 'sad', 'angry', 'calm', 'anxious', 'excited', 'sentimental', 'inspired', 'compassionate', 'romantic']

observed_values_dict = {}


for emotion in emotion_categories:
    observed_values = pd.crosstab(data['Language_' + emotion], data['Occupation'])
    observed_values_dict[emotion] = observed_values

for emotion in emotion_categories:
    print(f"Observed values for Language_{emotion}:")
    print(observed_values_dict[emotion])


Observed values for Language_happy:
Occupation      Entrepreneur  Private Sector  Public/Govt. Sector  Student  \
Language_happy                                                               
English                    7              17                    0       85   
Foreign                    1               0                    0       13   
Hindi                      3              19                    5       20   
Punjabi                    3               2                    2        7   
South Indian               1               7                    1        4   

Occupation      Unemployed/Not working  
Language_happy                          
English                              4  
Foreign                              0  
Hindi                               11  
Punjabi                              0  
South Indian                         0  
Observed values for Language_sad:
Occupation    Entrepreneur  Private Sector  Public/Govt. Sector  Student  \
Language_sad        

In [112]:
data['Age'] 

0      43
1      19
2      48
3      19
4      18
       ..
208    32
209    49
210    47
211    38
212    34
Name: Age, Length: 213, dtype: int64

In [113]:
observed_values_streaming_age = pd.crosstab(data['What do you prefer for streaming music ?'], data['Age_Group'])


chi2, p, dof, expected = scipy.stats.chi2_contingency(observed_values_streaming_age)


print(f"Chi-squared statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected values:")
print(expected)

Chi-squared statistic: 19.224224697460414
P-value: 0.00024570981584039686
Degrees of freedom: 3
Expected values:
[[50.95774648 81.15492958 35.85915493 33.02816901]
 [ 3.04225352  4.84507042  2.14084507  1.97183099]]


In [114]:
observed_values_streaming_age

Age_Group                                 15-19  20  26-39  40+
What do you prefer for streaming music ?                       
Audio                                        54  85     33   29
Video                                         0   1      5    6

In [115]:
data['How many hours do you stream music in a week (In hours) ?']

0       2.0
1      48.0
2      28.0
3      26.0
4      14.0
       ... 
208     1.0
209     5.5
210     5.5
211     7.0
212    11.0
Name: How many hours do you stream music in a week (In hours) ?, Length: 213, dtype: float64

## Objective 5 

## To see the influence of socio demographic factors with number of hours streaming on
## music

## Objective 6 

## To fit the distribution for hours of streaming on music

In [117]:
statistic, p_value = stats.shapiro(data['How many hours do you stream music in a week (In hours) ?'])

# Set a significance level (e.g., 0.05) to interpret the p-value
alpha = 0.05

if p_value > alpha:
    print("Data appears to be normally distributed (fail to reject the null hypothesis)")
else:
    print("Data does not appear to be normally distributed (reject the null hypothesis)")


Data does not appear to be normally distributed (reject the null hypothesis)


In [124]:
from scipy.stats import chisquare
import numpy as np


chi2_stat, p_value = chisquare(data['How many hours do you stream music in a week (In hours) ?'])

print(f"Chi-square test statistic: {chi2_stat}")
print(f"P-value: {p_value}")

alpha = 0.05  

if p_value < alpha:
    print("The dataset does not fit the chi-square distribution (Reject the null hypothesis)")
else:
    print("The dataset fits the chi-square distribution (Fail to reject the null hypothesis)")


Chi-square test statistic: 3722.587247324614
P-value: 0.0
The dataset does not fit the chi-square distribution (Reject the null hypothesis)
